<?php

/**
 * @file
 * Hooks and API functions for Rooms Variable Rate module.
 */

include_once 'rooms_variable_rate.field.inc';

define('ROOMS_VARIABLE_RATE_DISCOUNT', 'discount');
define('ROOMS_VARIABLE_RATE_FLAT_RATE', 'flat_rate');
define('ROOMS_VARIABLE_RATE_FIELD_NAME', 'rooms_variable_rate');

/**
 * Implements hook_menu().
 */
function rooms_variable_rate_menu() {
  $items = array();

  // Edit unit access pricing management.
  $items['admin/rooms/units/unit/%rooms_unit/variable_rate'] = array(
    'title' => 'Manage Variable Pricing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rooms_variable_rate_pricing_form', 4),
    'access callback' => 'rooms_unit_access',
    'access arguments' => array('update pricing', 4),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => '30',
    'file' => 'rooms_variable_rate.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function rooms_variable_rate_menu_alter(&$items) {
  // Disables Bulk pricing management feature.
  unset($items['admin/rooms/units/bulk_pricing_management']);
  // Disables Pricing calendar output.
  unset($items['rooms/units/unit/%rooms_unit/pricing/json/%/%']);
  // Disables default Manage Pricing tab.
  unset($items['admin/rooms/units/unit/%rooms_unit/pricing']);
}

/**
 * Implements hook_entity_insert().
 */
function rooms_variable_rate_entity_insert($entity, $type) {
  if ($type == 'rooms_unit_type') {
    rooms_variable_rate_create_instance('rooms_unit', $entity->type);
  }
}

/**
 * Implements hook_element_info().
 */
function rooms_variable_rate_element_info() {
  $elements = array();
  $elements['rooms_variable_rate'] = array(
    '#input' => TRUE,
    '#process' => array('rooms_variable_rate_process'),
  );
  return $elements;
}

/**
 * Generates the 'rooms_variable_rate' Form API element.
 */
function rooms_variable_rate_process($element, $form_state = array(), $complete_form = array()) {
  $element['minimum_stay'] = array(
    '#title' => t('Minimum stay'),
    '#title_display' => 'invisible',
    '#type' => 'textfield',
    '#field_prefix' => '<strong>' . t('If booking longer than') . '</strong>',
    '#field_suffix' => t('days'),
    '#size' => 2,
    '#default_value' => isset($element['#value']['minimum_stay']) ? $element['#value']['minimum_stay'] : '',
    '#element_validate' => array('element_validate_integer_positive'),
    '#weight' => 0,
  );

  $element['maximum_stay'] = array(
    '#title' => t('Maximum stay'),
    '#title_display' => 'invisible',
    '#type' => 'textfield',
    '#field_prefix' => '<strong>' . t('and booking shorter than') . '</strong>',
    '#field_suffix' => t('days'),
    '#size' => 2,
    '#default_value' => isset($element['#value']['maximum_stay']) ? $element['#value']['maximum_stay'] : '',
    '#element_validate' => array('element_validate_integer_positive'),
    '#weight' => 1,
  );

  $element['rate_type'] = array(
    '#type' => 'select',
    '#options' => array(
      ROOMS_VARIABLE_RATE_DISCOUNT => t('Discount (%)'),
      ROOMS_VARIABLE_RATE_FLAT_RATE => t('Flat rate'),
    ),
    '#default_value' => isset($element['#value']['rate_type']) ? $element['#value']['rate_type'] : '',
    '#field_prefix' => '<strong>' . t('provide') . '</strong>',
    '#weight' => 2,
    '#prefix' => '<div class="container-inline">',
  );

  $element['value'] = array(
    '#title' => t('Value'),
    '#title_display' => 'invisible',
    '#type' => 'textfield',
    '#size' => 2,
    '#default_value' => isset($element['#value']['value']) ? $element['#value']['value'] : '',
    '#element_validate' => array('element_validate_integer_positive'),
    '#weight' => 3,
    '#suffix' => '</div>',
  );

  return $element;
}

/**
 * Creates the Rooms variable Rate field instance.
 *
 * @param string $entity_type
 *   The entity type to attach the field instance.
 * @param string $bundle
 *   The specific bundle to attach the field instance.
 */
function rooms_variable_rate_create_instance($entity_type, $bundle) {
  rooms_variable_rate_create_field();
  if (field_read_instance($entity_type, ROOMS_VARIABLE_RATE_FIELD_NAME, $bundle) === FALSE) {
    $instance = array(
      'label' => 'Variable Rate',
      'widget' => array(
        'weight' => '1',
        'type' => 'rooms_variable_rate',
        'module' => 'rooms_variable_rate',
        'active' => 0,
        'settings' => array(),
      ),
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'display' => array(
        'default' => array(
          'label' => 'above',
          'type' => 'rooms_variable_rate',
          'settings' => array(),
          'module' => NULL,
          'weight' => 1,
        ),
      ),
      'required' => 0,
      'description' => '',
      'default_value' => NULL,
      'field_name' => ROOMS_VARIABLE_RATE_FIELD_NAME,
      'entity_type' => $entity_type,
      'bundle' => $bundle,
    );
    field_create_instance($instance);
  }
}

/**
 * Creates the default Rooms Variable Rate field.
 */
function rooms_variable_rate_create_field() {
  if (field_read_field(ROOMS_VARIABLE_RATE_FIELD_NAME) === FALSE) {
    $field = array(
      'settings' => array(),
      'field_name' => ROOMS_VARIABLE_RATE_FIELD_NAME,
      'type' => 'rooms_variable_rate',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'locked' => '1',
    );

    field_create_field($field);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for rooms_unit_edit_form().
 */
function rooms_variable_rate_form_rooms_unit_edit_form_alter(&$form, &$form_state) {
  if (isset($form[ROOMS_VARIABLE_RATE_FIELD_NAME])) {
    $form[ROOMS_VARIABLE_RATE_FIELD_NAME]['#access'] = FALSE;
  }
}
